# Generated by Django 3.1.4 on 2020-12-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
